if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    GIT_PROMPT_THEME=Single_line_Ubuntu
    GIT_PROMPT_SHOW_UPSTREAM=1

    source $HOME/.bash-git-prompt/gitprompt.sh
fi

# Use bash-completion, if available
[[ $PS1 && -f ~/.nix-profile/share/bash-completion/bash_completion ]] && \
    . ~/.nix-profile/share/bash-completion/bash_completion

source scm_breeze

# add this configuration to ~/.bashrc
export HH_CONFIG=hicolor                                          # get more colors
shopt -s histappend                                               # append new history items to .bash_history
export HISTCONTROL=ignorespace:ignoredups                         # leading space hides commands from history, no duplicate lines in the history.
export HISTFILESIZE=1000000                                       # increase history file size (default is 500)
export HISTSIZE=${HISTFILESIZE}                                   # increase history size (default is 500)
export HISTTIMEFORMAT="%F %T "                                    # setting up timestamp for history
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}" # mem/file sync
# if this is interactive shell, then bind hh to Ctrl-r (for Vi mode check doc)
if [[ $- =~ .*i.* ]]; then bind '"\C-r": "\C-a hh -- \C-j"'; fi
